#!/usr/bin/env node

// Refreshes data/repositories.json (the raw topic snapshot) and the review
// queue (data/review/pending.json + pending.md). This script only deals with
// raw data — CATALOG.md, its catalog/ volumes, and TOP200.md are NOT generated
// here; they are regenerated by scripts/merge.mjs after the maintainer has
// reviewed the queue and recorded decisions in data/approved.json /
// data/curated.json.
//
// README.md, README_EN.md, and SHOWCASE.md are maintained by hand and are
// never touched by any script. See data/review/README.md for the convention.

import { appendFile, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchWithRetry, githubHeaders } from './github.mjs';
import { loadState, writePending } from './render.mjs';
import { formatStarAnomalySummary } from './star-anomaly.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const query = 'topic:dsh-plugin';
const fromSnapshot = process.argv.includes('--from-snapshot');

const apiHeaders = githubHeaders();

// The Search API allows 30 requests/minute even when authenticated, well below the
// 5000/hour core limit — serialize every call through a shared, paced queue so
// bisected/parallel fetches below never burst past it. The pacing delay sits in a
// finally block: a request that just failed is exactly when the next one must not
// go out early, because a secondary rate limit is the likeliest reason it failed.
const SEARCH_REQUEST_INTERVAL_MS = 2100;
let requestQueue = Promise.resolve();
function throttled(task) {
  const run = requestQueue.then(async () => {
    try {
      return await task();
    } finally {
      await new Promise((resolve) => setTimeout(resolve, SEARCH_REQUEST_INTERVAL_MS));
    }
  });
  requestQueue = run.catch(() => {});
  return run;
}

// Transient failures are retried inside fetchWithRetry; one that survives the
// retries is still fatal here. A search page we cannot read silently truncates
// the snapshot, and a truncated snapshot is worse than keeping yesterday's file.
async function fetchPage(q, page) {
  return throttled(async () => {
    const response = await fetchWithRetry(
      `https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&per_page=100&page=${page}`,
      { headers: apiHeaders },
    );
    if (!response.ok) throw new Error(`GitHub API ${response.status}: ${await response.text()}`);
    return response.json();
  });
}

const toGithubDate = (date) => date.toISOString().replace(/\.\d{3}Z$/, 'Z');
const partitionWarnings = [];

// Splitting a range at the midpoint of its *time* span wastes requests whenever
// the creation dates are skewed, and this topic's are extreme: almost every
// repository was created in the last few weeks, while a long tail of older
// projects (some from 2017) adopted the topic years after they were created.
// Bisecting 18 years by time therefore spends a dozen requests walking down
// mostly empty windows before it reaches the crowd.
//
// Splitting at the median *count* instead — read off the previous snapshot's
// created_at distribution — turns that deep, lopsided tree into a shallow
// balanced one: measured against the stored 10,945-repository snapshot, 150
// requests drop to 127. The scanned bounds are unchanged, so this is purely a
// question of where the cut goes; nothing can fall outside the window. With no
// previous snapshot to learn from (first run), it degrades to the time midpoint.
function makeSplitter(previousRepositories) {
  const timeMidpoint = (minMs, maxMs) => minMs + Math.floor((maxMs - minMs) / 2);
  const times = previousRepositories
    .map((repo) => Date.parse(repo.created_at))
    .filter((value) => Number.isFinite(value))
    .sort((a, b) => a - b);
  if (times.length < 2) return timeMidpoint;
  const lowerBound = (value) => {
    let low = 0;
    let high = times.length;
    while (low < high) {
      const mid = (low + high) >> 1;
      if (times[mid] < value) low = mid + 1;
      else high = mid;
    }
    return low;
  };
  return (minMs, maxMs) => {
    const start = lowerBound(minMs);
    const end = lowerBound(maxMs + 1000);
    if (end - start < 2) return timeMidpoint(minMs, maxMs);
    const median = times[start + ((end - start) >> 1)];
    // The median becomes the right half's first second, so the cut is one
    // second before it; fall back whenever that would not shrink both halves.
    return median <= minMs || median > maxMs ? timeMidpoint(minMs, maxMs) : median - 1000;
  };
}

// The overall dsh-plugin topic can hold more than 1000 repositories, which a single
// search query cannot return. Recursively bisect the created-date range — using the
// documented `created:A..B` range qualifier, since two separate `created:` clauses in
// one query do not combine reliably — until each partition's total_count fits under
// the cap, then merge the partial result sets. Only page 1 is fetched to check a
// partition's total_count; the remaining pages are fetched only for partitions that
// turn out to be small enough to keep, so branches that get bisected further don't
// waste requests pulling pages that will just be discarded.
async function fetchRange(baseQuery, minDate, maxDate, splitAt) {
  if (minDate.getTime() > maxDate.getTime()) return [];
  const rangeQuery = `${baseQuery} created:${toGithubDate(minDate)}..${toGithubDate(maxDate)}`;
  const first = await fetchPage(rangeQuery, 1);
  const total = first.total_count;
  if (total <= 1000) {
    const pageCount = Math.min(Math.ceil(total / 100), 10);
    const remaining = await Promise.all(
      Array.from({ length: Math.max(0, pageCount - 1) }, (_, index) => fetchPage(rangeQuery, index + 2)),
    );
    return [first, ...remaining].flatMap((page) => page.items);
  }
  const spanMs = maxDate.getTime() - minDate.getTime();
  // The split point is only ever an optimisation: clamp anything the splitter
  // returns that would not leave both halves strictly smaller back to the time
  // midpoint, so a bad hint can never be mistaken for an unsplittable window
  // (which would silently cap this branch at 1000 repositories).
  let midMs = splitAt(minDate.getTime(), maxDate.getTime());
  if (!Number.isFinite(midMs) || midMs < minDate.getTime() || midMs + 1000 > maxDate.getTime()) {
    midMs = minDate.getTime() + Math.floor(spanMs / 2);
  }
  const mid = new Date(midMs);
  const rightMin = new Date(mid.getTime() + 1000);
  if (spanMs < 2000 || rightMin.getTime() > maxDate.getTime()) {
    partitionWarnings.push(
      `${total} repositories were created within ${toGithubDate(minDate)}..${toGithubDate(maxDate)}, a window too narrow (1-second search resolution) to split further; only the first 1000 were fetched for this window.`,
    );
    return first.items;
  }
  const [left, right] = await Promise.all([
    fetchRange(baseQuery, minDate, mid, splitAt),
    fetchRange(baseQuery, rightMin, maxDate, splitAt),
  ]);
  return [...left, ...right];
}

function normalizeRepository(repo) {
  return {
    id: repo.id,
    full_name: repo.full_name,
    html_url: repo.html_url,
    description: repo.description,
    homepage: repo.homepage || null,
    language: repo.language,
    stargazers_count: repo.stargazers_count,
    forks_count: repo.forks_count,
    open_issues_count: repo.open_issues_count,
    license: repo.license?.spdx_id || null,
    archived: repo.archived,
    disabled: repo.disabled,
    created_at: repo.created_at,
    updated_at: repo.updated_at,
    pushed_at: repo.pushed_at,
    default_branch: repo.default_branch,
    size_kb: repo.size,
    topics: repo.topics || [],
  };
}

// The Search API's index lags behind reality: repositories that were recently
// pushed, renamed, or re-tagged can transiently drop out of topic search
// results (the topics page itself can show a higher count than the search API
// returns). Reconcile the search snapshot against the sources where a silent
// drop would hurt — every curated reference (approved.json / curated.json) plus
// the market-relevant tier of the previous snapshot — by fetching each missing
// candidate directly from the REST core API, which reports live topics and
// follows renames.
const PREVIOUS_SNAPSHOT_STAR_FLOOR = 3;

// How far the repository count may fall against the previous snapshot before
// the run is treated as a failed crawl rather than a real change. Deliberately
// looser than the market file's 0.6: this guards raw input, and the whole
// review pipeline sits downstream of it.
const SNAPSHOT_BREAKER_RATIO = 0.8;

class SnapshotCollapse extends Error {}

// Reconciliation is best-effort, so unlike a search page a probe that keeps
// failing must not take the run down with it: it costs one repository in
// today's snapshot, and the review queue's "approved but missing from the
// snapshot" list is exactly where that surfaces. A 404 is a real answer
// (deleted, renamed away, or private) and is never retried; anything else that
// survives the retries is reported back as a failure for the caller to warn on.
async function fetchRepo(fullName) {
  let response;
  try {
    response = await fetchWithRetry(`https://api.github.com/repos/${fullName}`, { headers: apiHeaders });
  } catch (error) {
    return { ok: false, reason: `network error (${error.message})` };
  }
  if (response.status === 404) return { ok: true, repo: null };
  if (!response.ok) return { ok: false, reason: `GitHub API ${response.status} after retries` };
  return { ok: true, repo: await response.json() };
}

async function reconcileSnapshot(items, previousRepositories) {
  const seenIds = new Set(items.map((item) => item.id));
  const seenNames = new Set(items.map((item) => item.full_name.toLowerCase()));
  const candidates = new Map();
  const addCandidate = (name) => {
    if (!seenNames.has(name.toLowerCase())) candidates.set(name.toLowerCase(), name);
  };
  const [approved, curated] = await Promise.all([
    readFile(resolve(root, 'data/approved.json'), 'utf8').then(JSON.parse),
    readFile(resolve(root, 'data/curated.json'), 'utf8').then(JSON.parse),
  ]);
  for (const name of Object.keys(approved)) addCandidate(name);
  for (const section of Object.values(curated)) {
    for (const name of Object.keys(section)) addCandidate(name);
  }
  for (const repo of previousRepositories) {
    if (repo.stargazers_count >= PREVIOUS_SNAPSHOT_STAR_FLOOR) addCandidate(repo.full_name);
  }
  const recovered = [];
  const renames = [];
  const failures = [];
  for (const name of candidates.values()) {
    const result = await fetchRepo(name);
    if (!result.ok) {
      failures.push(`${name}: ${result.reason}`);
      continue;
    }
    const repo = result.repo;
    if (!repo || !repo.topics?.includes('dsh-plugin') || seenIds.has(repo.id)) continue;
    if (repo.full_name.toLowerCase() !== name.toLowerCase()) renames.push(`${name} -> ${repo.full_name}`);
    recovered.push(repo);
    seenIds.add(repo.id);
    seenNames.add(repo.full_name.toLowerCase());
  }
  return { recovered, renames, failures, checked: candidates.size };
}

async function refreshSnapshot() {
  const fetchedAt = new Date();
  let previousSnapshot = { repositories: [], fetched_at: null };
  try {
    previousSnapshot = JSON.parse(await readFile(resolve(root, 'data/repositories.json'), 'utf8'));
  } catch {
    // first run — nothing to reconcile against
  }
  const previousRepositories = previousSnapshot.repositories ?? [];
  const items = await fetchRange(
    query,
    new Date('2008-01-01T00:00:00Z'),
    fetchedAt,
    makeSplitter(previousRepositories),
  );
  const { recovered, renames, failures, checked } = await reconcileSnapshot(items, previousRepositories);
  for (const rename of renames) {
    partitionWarnings.push(
      `${rename} — renamed on GitHub; update the approved.json / curated.json keys manually.`,
    );
  }
  // Aggregated into one line: a rate-limited run can fail hundreds of probes,
  // and hundreds of warnings would bury the renames above.
  if (failures.length) {
    partitionWarnings.push(
      `${failures.length} of ${checked} reconciliation probes failed after retries and were skipped — those repositories are absent from today's snapshot and will show up as missing from it (${failures.slice(0, 5).join('; ')}${failures.length > 5 ? '; …' : ''}).`,
    );
  }
  // Stored in a stable order (ascending id), not by stars: star counts move
  // every day, so a star-sorted file reshuffles thousands of entries and turns
  // a daily diff of a few hundred changed fields into tens of thousands of
  // moved lines. Every consumer (render.mjs, market.mjs) sorts explicitly for
  // display, so the stored order carries no presentation meaning.
  const byId = new Map([...items, ...recovered].map((item) => [item.id, item]));
  const repositories = [...byId.values()]
    .map(normalizeRepository)
    .sort((a, b) => a.id - b.id);
  if (recovered.length) {
    console.log(
      `Reconciled ${recovered.length} of ${checked} search-missing candidates back into the snapshot via the REST API.`,
    );
  }
  // Circuit breaker, mirroring the one in scripts/market.mjs §6: a snapshot
  // that collapsed against yesterday's smells like a half-failed crawl (a
  // search index wobble, an exhausted rate limit that ate a whole partition),
  // and yesterday's file is the better answer. The topic only ever grows, so
  // any real drop is small — deletions and un-tagging move a handful of
  // repositories a day, not a fifth of the corpus. Reconciliation already
  // guards the curated tier; this guards everything else, including the
  // pending queue, where a silent collapse would reset first_seen dates.
  if (previousRepositories.length && repositories.length < previousRepositories.length * SNAPSHOT_BREAKER_RATIO) {
    throw new SnapshotCollapse(
      `the fetched snapshot holds ${repositories.length} repositories, below ${Math.round(SNAPSHOT_BREAKER_RATIO * 100)}% of the previous snapshot (${previousRepositories.length}) — refusing to overwrite it; the previous data/repositories.json is left untouched.`,
    );
  }
  return {
    snapshot: {
      source: 'https://github.com/topics/dsh-plugin',
      query,
      fetched_at: fetchedAt.toISOString(),
      total_count: repositories.length,
      repositories,
    },
    previousRepositories,
    previousDate: typeof previousSnapshot.fetched_at === 'string' ? previousSnapshot.fetched_at.slice(0, 10) : null,
  };
}

// data/repositories.json stores every repository the topic search returned, untouched:
// no description filter, no exclusion list, no approval gate. The review queue and the
// user-facing pages are derived from it (plus data/approved.json / data/curated.json),
// so manual analysis of the raw data always has the complete picture.
let snapshot;
let previousRepositories = null;
let previousDate = null;
if (fromSnapshot) {
  snapshot = JSON.parse(await readFile(resolve(root, 'data/repositories.json'), 'utf8'));
} else {
  try {
    const refreshed = await refreshSnapshot();
    snapshot = refreshed.snapshot;
    previousRepositories = refreshed.previousRepositories;
    previousDate = refreshed.previousDate;
  } catch (error) {
    if (!(error instanceof SnapshotCollapse)) throw error;
    // Nothing is written: neither the snapshot nor the review queue, so the
    // two stay consistent with each other and the workflow's commit step
    // never runs. Failing loudly is the point — a silent keep would hide a
    // broken crawl for as long as it kept happening.
    console.error(`Snapshot refresh aborted: ${error.message}`);
    if (process.env.GITHUB_STEP_SUMMARY) {
      await appendFile(
        process.env.GITHUB_STEP_SUMMARY,
        `### ⚠️ Snapshot refresh aborted\n\n${error.message}\n`,
      );
    }
    process.exit(1);
  }
  await writeFile(resolve(root, 'data/repositories.json'), `${JSON.stringify(snapshot, null, 2)}\n`);
}

const state = await loadState();
const pendingOptions = fromSnapshot ? {} : { previousRepositories, previousDate };
const { pending, missing, starAnomalies } = await writePending(state, pendingOptions);

const anomalySummary = formatStarAnomalySummary(starAnomalies);
console.log(
  `${fromSnapshot ? 'Generated from snapshot' : 'Updated snapshot'} with ${snapshot.repositories.length} repositories at ${snapshot.fetched_at}; review queue holds ${pending.length} pending, ${missing.length} approved repositories missing from the snapshot${anomalySummary ? `; ${anomalySummary}` : ''}.`,
);
if (anomalySummary) console.warn(`Warning: ${anomalySummary}`);
if (starAnomalies?.alerts?.length && process.env.GITHUB_STEP_SUMMARY) {
  const lines = starAnomalies.alerts
    .slice(0, 40)
    .map((alert) => {
      const delta = alert.delta == null ? 'n/a' : `${alert.delta >= 0 ? '+' : ''}${alert.delta}`;
      return `- [${alert.full_name}](${alert.html_url}) — ${alert.queue}, ${alert.stars}★ (Δ ${delta}), ${alert.signals.join(', ')}`;
    });
  await appendFile(
    process.env.GITHUB_STEP_SUMMARY,
    `### ⚠️ Star-growth alerts\n\n${anomalySummary} See \`data/review/pending.md\`. Extra analysis required before these land on the star board.\n\n${lines.join('\n')}${starAnomalies.alerts.length > 40 ? `\n- … and ${starAnomalies.alerts.length - 40} more` : ''}\n`,
  );
}

const warnings = [...partitionWarnings];
if (warnings.length) {
  for (const warning of warnings) console.warn(`Warning: ${warning}`);
  if (process.env.GITHUB_STEP_SUMMARY) {
    await appendFile(
      process.env.GITHUB_STEP_SUMMARY,
      `### Snapshot warnings\n\n${warnings.map((warning) => `- ${warning}`).join('\n')}\n`,
    );
  }
}
