#!/usr/bin/env node

// Refreshes data/repositories.json (the raw topic snapshot) and the review
// queue (data/review/pending.json + pending.md). This script only deals with
// raw data — CATALOG.md and TOP200.md are NOT generated here; they are
// regenerated by scripts/merge.mjs after the maintainer has reviewed the
// queue and recorded decisions in data/approved.json / data/curated.json.
//
// README.md, README_EN.md, and SHOWCASE.md are maintained by hand and are
// never touched by any script. See data/review/README.md for the convention.

import { appendFile, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { computePending, loadState, writePending } from './render.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const query = 'topic:dsh-plugin';
const fromSnapshot = process.argv.includes('--from-snapshot');

const apiHeaders = {
  Accept: 'application/vnd.github+json',
  'User-Agent': 'awesome-dsh-plugin',
  'X-GitHub-Api-Version': '2022-11-28',
};
if (process.env.GITHUB_TOKEN) apiHeaders.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;

// The Search API allows 30 requests/minute even when authenticated, well below the
// 5000/hour core limit — serialize every call through a shared, paced queue so
// bisected/parallel fetches below never burst past it.
const SEARCH_REQUEST_INTERVAL_MS = 2100;
let requestQueue = Promise.resolve();
function throttled(task) {
  const run = requestQueue.then(async () => {
    const result = await task();
    await new Promise((resolve) => setTimeout(resolve, SEARCH_REQUEST_INTERVAL_MS));
    return result;
  });
  requestQueue = run.catch(() => {});
  return run;
}

async function fetchPage(q, page) {
  return throttled(async () => {
    const response = await fetch(
      `https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&per_page=100&page=${page}`,
      { headers: apiHeaders },
    );
    if (!response.ok) throw new Error(`GitHub API ${response.status}: ${await response.text()}`);
    return response.json();
  });
}

const toGithubDate = (date) => date.toISOString().replace(/\.\d{3}Z$/, 'Z');
const partitionWarnings = [];

// The overall dsh-plugin topic can hold more than 1000 repositories, which a single
// search query cannot return. Recursively bisect the created-date range — using the
// documented `created:A..B` range qualifier, since two separate `created:` clauses in
// one query do not combine reliably — until each partition's total_count fits under
// the cap, then merge the partial result sets. Only page 1 is fetched to check a
// partition's total_count; the remaining pages are fetched only for partitions that
// turn out to be small enough to keep, so branches that get bisected further don't
// waste requests pulling pages that will just be discarded.
async function fetchRange(baseQuery, minDate, maxDate) {
  if (minDate.getTime() > maxDate.getTime()) return [];
  const rangeQuery = `${baseQuery} created:${toGithubDate(minDate)}..${toGithubDate(maxDate)}`;
  const first = await fetchPage(rangeQuery, 1);
  const total = first.total_count;
  if (total <= 1000) {
    const pageCount = Math.min(Math.ceil(total / 100), 10);
    const remaining = await Promise.all(
      Array.from({ length: Math.max(0, pageCount - 1) }, (_, index) => fetchPage(rangeQuery, index + 2)),
    );
    return [first, ...remaining].flatMap((page) => page.items);
  }
  const spanMs = maxDate.getTime() - minDate.getTime();
  const mid = new Date(minDate.getTime() + Math.floor(spanMs / 2));
  const rightMin = new Date(mid.getTime() + 1000);
  if (spanMs < 2000 || rightMin.getTime() > maxDate.getTime()) {
    partitionWarnings.push(
      `${total} repositories were created within ${toGithubDate(minDate)}..${toGithubDate(maxDate)}, a window too narrow (1-second search resolution) to split further; only the first 1000 were fetched for this window.`,
    );
    return first.items;
  }
  const [left, right] = await Promise.all([
    fetchRange(baseQuery, minDate, mid),
    fetchRange(baseQuery, rightMin, maxDate),
  ]);
  return [...left, ...right];
}

function normalizeRepository(repo) {
  return {
    id: repo.id,
    full_name: repo.full_name,
    html_url: repo.html_url,
    description: repo.description,
    homepage: repo.homepage || null,
    language: repo.language,
    stargazers_count: repo.stargazers_count,
    forks_count: repo.forks_count,
    open_issues_count: repo.open_issues_count,
    license: repo.license?.spdx_id || null,
    archived: repo.archived,
    disabled: repo.disabled,
    created_at: repo.created_at,
    updated_at: repo.updated_at,
    pushed_at: repo.pushed_at,
    default_branch: repo.default_branch,
    size_kb: repo.size,
    topics: repo.topics || [],
  };
}

// The Search API's index lags behind reality: repositories that were recently
// pushed, renamed, or re-tagged can transiently drop out of topic search
// results (the topics page itself can show a higher count than the search API
// returns). Reconcile the search snapshot against the sources where a silent
// drop would hurt — every curated reference (approved.json / curated.json) plus
// the market-relevant tier of the previous snapshot — by fetching each missing
// candidate directly from the REST core API, which reports live topics and
// follows renames.
const PREVIOUS_SNAPSHOT_STAR_FLOOR = 3;

async function fetchRepo(fullName) {
  const response = await fetch(`https://api.github.com/repos/${fullName}`, { headers: apiHeaders });
  if (response.status === 404) return null;
  if (!response.ok) throw new Error(`GitHub API ${response.status} for ${fullName}: ${await response.text()}`);
  return response.json();
}

async function reconcileSnapshot(items, previousRepositories) {
  const seenIds = new Set(items.map((item) => item.id));
  const seenNames = new Set(items.map((item) => item.full_name.toLowerCase()));
  const candidates = new Map();
  const addCandidate = (name) => {
    if (!seenNames.has(name.toLowerCase())) candidates.set(name.toLowerCase(), name);
  };
  const [approved, curated] = await Promise.all([
    readFile(resolve(root, 'data/approved.json'), 'utf8').then(JSON.parse),
    readFile(resolve(root, 'data/curated.json'), 'utf8').then(JSON.parse),
  ]);
  for (const name of Object.keys(approved)) addCandidate(name);
  for (const section of Object.values(curated)) {
    for (const name of Object.keys(section)) addCandidate(name);
  }
  for (const repo of previousRepositories) {
    if (repo.stargazers_count >= PREVIOUS_SNAPSHOT_STAR_FLOOR) addCandidate(repo.full_name);
  }
  const recovered = [];
  const renames = [];
  for (const name of candidates.values()) {
    const repo = await fetchRepo(name);
    if (!repo || !repo.topics?.includes('dsh-plugin') || seenIds.has(repo.id)) continue;
    if (repo.full_name.toLowerCase() !== name.toLowerCase()) renames.push(`${name} -> ${repo.full_name}`);
    recovered.push(repo);
    seenIds.add(repo.id);
    seenNames.add(repo.full_name.toLowerCase());
  }
  return { recovered, renames, checked: candidates.size };
}

async function refreshSnapshot() {
  const fetchedAt = new Date();
  let previousRepositories = [];
  try {
    previousRepositories =
      JSON.parse(await readFile(resolve(root, 'data/repositories.json'), 'utf8')).repositories ?? [];
  } catch {
    // first run — nothing to reconcile against
  }
  const items = await fetchRange(query, new Date('2008-01-01T00:00:00Z'), fetchedAt);
  const { recovered, renames, checked } = await reconcileSnapshot(items, previousRepositories);
  for (const rename of renames) {
    partitionWarnings.push(
      `${rename} — renamed on GitHub; update the approved.json / curated.json keys manually.`,
    );
  }
  const byId = new Map([...items, ...recovered].map((item) => [item.id, item]));
  const repositories = [...byId.values()]
    .map(normalizeRepository)
    .sort((a, b) => b.stargazers_count - a.stargazers_count || a.full_name.localeCompare(b.full_name));
  if (recovered.length) {
    console.log(
      `Reconciled ${recovered.length} of ${checked} search-missing candidates back into the snapshot via the REST API.`,
    );
  }
  return {
    source: 'https://github.com/topics/dsh-plugin',
    query,
    fetched_at: fetchedAt.toISOString(),
    total_count: repositories.length,
    repositories,
  };
}

// data/repositories.json stores every repository the topic search returned, untouched:
// no description filter, no exclusion list, no approval gate. The review queue and the
// user-facing pages are derived from it (plus data/approved.json / data/curated.json),
// so manual analysis of the raw data always has the complete picture.
const snapshot = fromSnapshot
  ? JSON.parse(await readFile(resolve(root, 'data/repositories.json'), 'utf8'))
  : await refreshSnapshot();

if (!fromSnapshot) {
  await writeFile(resolve(root, 'data/repositories.json'), `${JSON.stringify(snapshot, null, 2)}\n`);
}

const state = await loadState();
const { pending, missing } = computePending(state);
await writePending(state);

console.log(
  `${fromSnapshot ? 'Generated from snapshot' : 'Updated snapshot'} with ${snapshot.repositories.length} repositories at ${snapshot.fetched_at}; review queue holds ${pending.length} pending, ${missing.length} approved repositories missing from the snapshot.`,
);

const warnings = [...partitionWarnings];
if (warnings.length) {
  for (const warning of warnings) console.warn(`Warning: ${warning}`);
  if (process.env.GITHUB_STEP_SUMMARY) {
    await appendFile(
      process.env.GITHUB_STEP_SUMMARY,
      `### Snapshot warnings\n\n${warnings.map((warning) => `- ${warning}`).join('\n')}\n`,
    );
  }
}
